import tkinter 
root = tkinter.Tk()
name_label = tkinter.Label(root, text="enter name")
name_label.pack()
name_textbox = tkinter.Entry(root)
name_textbox.pack()
phone_label = tkinter.Label(root, text = "enter phone number")
phone_label.pack()
phone_textbox = tkinter.Entry(root)
phone_textbox.pack()
email_label = tkinter.Label(root, text = "enter email")
email_label.pack()
email_textbox = tkinter.Entry(root)
email_textbox.pack()
submit_button = tkinter.Button(root, text = "submit")
submit_button.pack()
root.mainloop()